name: Build

on:
  pull_request:
  push:
env:
  CI: true
  TERM: dumb

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --stacktrace build

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: modules/*/build/test-results/**/*.xml

      - name: Upload test tesults
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          if-no-files-found: error
          path: |
            modules/*/build/reports/
            modules/*/build/test-results/**/*.xml

      - name: Upload NBM archives
        uses: actions/upload-artifact@v2
        with:
          name: nbm
          path: build/nbm
